id: PBEBBB6A9
initial_creation_type: input
source_metadata:
  title: Lhatsün Namkha Jigme Series
  language: pt
  description: 'Texts associated with the famous yogi Lhatsün Namkha Jigme (lha btsun
    nam mkha'' ''jigs med, 1597–1650), who is credited with ''opening the hidden land''
    of Sikkim:'
  volume:
    4ffb0f1febfe4a38ad438a5c856d2163:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    b2c32005365e40edaec5efc3c01ef667:
      title: Summoning Prosperity
      parent: Prayers and Practices
    53f99d3ee45048cc987dda9716ddc3e8:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Sang Offering
    701e4315e8ca49ed9c8f2200bcced710:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Sang Offering
    c03600f43bf9444eb63263b8b4e2899d:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
created_at: '2022-03-01T00:35:25.498153'
last_modified_at: '2022-03-01T00:35:25.498155'
